version: '3'

services:

  db:
    image: influxdb:2.7
    container_name: duplicati-dashboard-db
    restart: unless-stopped
    ports:
      - '4001:8086'
    environment: 
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
    volumes:
      - ./db/lib:/var/lib/influxdb2
      - ./db/etc:/etc/influxdb2
      # - ./config.yml:/etc/influxdb2/config.yml
    # networks:
    #   - proxy

  app:
    image: duplicati-dashboard
    container_name: duplicati-dashboard-app
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    ports:
      - 4000:3000 
    depends_on:
      - db
    # networks:
    #   - proxy

# networks:
#   proxy: 
#     name: nginx-prox-mgmt-3_default # whatever proxy container network
#     driver: bridge
#     external: true